### ISSUE TITLE
Bug: Vanilla Nanofab mission scripts respond to Luxury Nanofab side mission

### ISSUE THREAD

**Issue by Hekateras** [Mobbstar/InvisibleInc-MoreMissions#188]
Cause: Scripts only check for 'storeType = "large"' trait
Possible fix: Overwriting vanilla nanofab scripts to be more selective (at least 2 scripts)
Other possible fix: Prevent luxury nanofab from co-occuring with nanofab missions

IIRC removing the large store trait from luxury nanofab is not an easy option because the storeType trait determines the shop UI that appears, but this bears double-checking

**Comment by qoala** [comment]
It's possible that there's something I haven't found yet, but:
* `hud.lua`: Sim Constructor already overloads the `EV_ITEMS_PANEL` handler to support "extraserver" for PE. Also, this shows the basic "shop" if the type doesn't match any of the various program shop types, so "large" shouldn't affect this.
* `shop_panel.shop:init`: Passes the storeType to the base items panel, but the base items panel doesn't use that argument. No effect.
* `simstore.createStoreItems` relies on the storeType matching an entry in the giant `STORE_ITEM` table. The store type table here maps store sizes to how many of each kind of item/program to roll.

I'd guess that `simstore.createStoreItems` was the part that broke from changing storeType to a custom value.

If we added our own entries to `STORE_ITEM.storeType`, we could even clean up our `populateFancyFab` code, since we wouldn't need to do a bunch of generate iterations.

```lua
STORE_ITEM.storeType.MM_luxuryItem = {
  itemAmount = 16,
  progAmount = 0,
  weaponAmount = 0,
  augmentAmount = 0,
}
STORE_ITEM.storeType.MM_luxuryWpn = {
  itemAmount = 0,
  progAmount = 0,
  weaponAmount = 16,
  augmentAmount = 0,
}
STORE_ITEM.storeType.MM_luxuryAug = {
  itemAmount = 0,
  progAmount = 0,
  weaponAmount = 0,
  augmentAmount = 16,
}
```

---

It's possible that I overlooked something, but those were the spots I noticed the `storeType` value being relevant.
