### ISSUE TITLE
Assassination "Heat Signature" doesn't follow the target

### ISSUE THREAD

**Issue by qoala** [Mobbstar/InvisibleInc-MoreMissions#41]
Assassination mission script attaches the same `HEAT_SIGNATURE_DETECTED` label to the target as the vanilla CFO mission. 

However, it doesn't replicate the `followHeatSig` trigger from the vanilla mission.
As a result, the label stays in its original position until cleared. It also sometimes fails to be cleared, though this may be from an unrelated bug (https://discord.com/channels/313015356052471828/349605172256964618/844936161515667496)

---

CFO uses `displayHUDInstruction` for the label, of which a mission can manage 1 at a time on arbitrary tiles.

Assassination already uses `displayHUDInstruction` to explain "use authorized body" on the safe door.

Assassination currently uses `unit:createTab` for "heat signature detected", which attaches the label directly to the CEO but ends up clearing it each turn or if the target is observed.

**Comment by Sizzlefrost** [comment]
Now pushed.

As far as I know, I've covered the situations where the tab would be off (observe / guard situation change / movement / turn start), but testing wasn't extensive and, more concerningly, the tab still _refreshes_ whenever one of these things happen, rather than staying as it was. Close enough, for now.

**Comment by Sizzlefrost** [comment]
okay I really need to stop working on this, final pull request and this should be closed now
